env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=netsim=trace
    - RUST_TEST_THREADS=1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcap-dev
language: rust
rust:
    - stable
    - beta
    - nightly
cache: cargo
script:
    - cargo test -- --nocapture

