env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
language: rust
sudo: false
cache:
  cargo: true
before_script:
  - sudo apt-get update
  - sudo apt-get install -y libcap-dev
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - rustup component add clippy
script:
  - set -x;
    cargo test --release --verbose --no-default-features
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then
      cargo clippy --verbose --release --all-targets ;
    fi
  - cargo check --examples
before_cache:
  - cargo prune
