[package]
name = "netsim"
version = "0.1.0"
authors = ["Andrew Cann <shum@canndrew.org>"]
description = "Network simulator"

[dependencies]
libc = "*"
unwrap = "1.1"
get_if_addrs = "0.4"
tun = "*"
lazy_static = "*"
future-utils = "*"
futures = "*"
tokio-core = "*"
tokio-io = "*"
void = "*"
net-literals = "*"
rand = "0.4"
rand_derive = "*"
#rand = { path = "../rand" }
#rand_derive = { path = "../rand/rand-derive" }
ioctl-sys = "*"
bytes = "*"
#backtrace-sys = "=0.1.15"
backtrace = "0.3.3"
mio = "*"
quick-error = "*"
log = "*"
env_logger = "*"

[build-dependencies]
bindgen = "0.30.0"

