[package]
name = "netsim"
version = "0.1.9"
authors = ["Andrew Cann <shum@canndrew.org>"]
description = "Network simulator"
repository = "https://github.com/canndrew/netsim"
license = "GPL-2.0"
keywords = ["network", "ip", "testing"]
categories = ["development-tools::testing", "network-programming", "simulation"]
readme = "README.md"

[dependencies]
libc = "0.2.36"
unwrap = "1.1"
get_if_addrs = "0.4"
future-utils = "0.8.0"
futures = "0.1.18"
tokio-core = "0.1.12"
tokio-io = "0.1.5"
void = "1.0.2"
net-literals = "0.1.2"
rand = "0.4"
rand_derive = "0.3.1"
ioctl-sys = "0.5.2"
bytes = "0.4.6"
mio = "0.6.13"
quick-error = "1.2.1"
log = "0.4.1"
env_logger = "0.4.0"
capabilities = "0.3.0"
byteorder = "1.2.1"
statrs = "0.9.0"
clippy = { version = "0.0.187", optional = true }

[build-dependencies]
bindgen = "0.30.0"

[dev-dependencies]
bincode = "0.9.2"

